// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjezusozpvbcfsyxqgha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qZXp1c296cHZiY2ZzeXhxZ2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzQyMzIsImV4cCI6MjA2Njk1MDIzMn0.9o7RWjpUl4hoHa1EMDQxXplgf1ni7BDluerTlFKnKPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});